betcroquet_app/urls.py
from django.contrib import admin
from django.urls import path,include
from betcroquet_app import views
#template tag
app_name = 'betcroquet_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('bet/<int:gameCode>',views.betview,name='betView'),
    path('addBet',views.addBetview,name='addBetview'),
    #path('register/',views.register,name='register'),
    #path('user_login/',views.user_login,name='user_login'),

]

lastpotatodev/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main_app import views as mViews
from betcroquet_app import views as bViews
from user_mgmt_app import views as uViews

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',bViews.index,name='index'),
    path('admin/', admin.site.urls),
    path('main_app/',include('main_app.urls')),
    path('user_mgmt_app/',include('user_mgmt_app.urls')),
    path('betcroquet_app/',include('betcroquet_app.urls')),
    #path('logout/',views.user_logout,name='logout'),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.contrib import admin
from django.urls import path,include
from main_app import views
#template tag
app_name = 'main_app'

urlpatterns = [
    path('',views.index,name='index'),
    #path('register/',views.register,name='register'),
    #path('user_login/',views.user_login,name='user_login'),

]

user_mgmt_app/urls.py
from django.contrib import admin
from django.urls import path,include
from user_mgmt_app import views
#template tag
app_name = 'user_mgmt_app'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('user_logout/',views.user_logout,name='user_logout'),
]

betcroquet_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.

class BetTemplate(models.Model):

    name        = models.CharField(max_length = 100)
    description = models.TextField(max_length=500,null=True)
    state       = models.BooleanField(default = False)
    openDate    = models.DateField(null=True)
    endDate     = models.DateField(null=False)
    image       = models.ImageField(upload_to = 'bet_templates/', default = 'default.jpg',)

    def __str__(self):
        return self.name

class BetCollection(models.Model):

    """Collection of the bets of users"""
    gameCode    = models.CharField(max_length=100,unique= True)
    name        = models.CharField(max_length=100)
    closeDate   = models.DateField(null=True)
    max_users   = models.IntegerField(null=True)
    description = models.TextField(max_length=500,null=True)

    template    = models.ForeignKey(BetTemplate,related_name="betCollTemplate",on_delete=models.CASCADE,null=True)
    def __str__(self):
        return '{}:{}'.format(self.gameCode,self.name)



class Bet(models.Model):

    """user personal bet"""
    betCollection   = models.ForeignKey(BetCollection,related_name='betCollBet',on_delete=models.CASCADE)
    user            = models.OneToOneField(User,related_name='user',on_delete=models.CASCADE)
    hits            = models.IntegerField(default=0)
    def __str__(self):
        return 'User:{}, Game:{}'.format(self.user.username,self.betCollection.gameCode)



class Category(models.Model):

    BetTemplate     = models.ForeignKey(BetTemplate,related_name='BetTemplateCategory',on_delete=models.CASCADE,null=True)
    name            = models.TextField(max_length=300)
    description     = models.TextField(max_length=900,null=True,blank=True)
    #winner      = models.ForeignKey(Option,related_name='option',null=True)
    image           = models.ImageField(upload_to = 'category_pics/', default = 'category_pics/None/no-img.jpg')
    def __str__(self):
        return self.name

class Option(models.Model):

    category    = models.ManyToManyField(Category,related_name='optionCategory')
    name        = models.TextField(max_length=500)
    description = models.TextField(max_length=900,null=True,blank=True)
    image       = models.ImageField(upload_to = 'option_pics/', default = 'option_pics/None/no-img.jpg')
    video       = models.TextField(max_length=900,null=True,blank=True)
    def __str__(self):
        return self.name

class BetSelection(models.Model):
    """actual user selection"""
    bet         = models.OneToOneField(Bet,related_name = 'betSelection',on_delete = models.CASCADE)
    category    = models.OneToOneField(Category,related_name = 'categoryBet',on_delete = models.CASCADE)
    option      = models.OneToOneField(Option,related_name = 'optionBet',on_delete = models.CASCADE)
    def __str__(self):
        return 'user:{},c:{},o:{}'.format(self.bet.user.username,self.category.name,self.option.name)

class CategoryWinner(models.Model):
    category    = models.ForeignKey(Category,on_delete = models.CASCADE)
    option      = models.ForeignKey(Option,on_delete = models.CASCADE)

betcroquet_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from betcroquet_app.models import Bet
from django.core.files.images import get_image_dimensions

class AddBetForm(forms.Form):
    gameCode = forms.CharField(widget = forms.TextInput(attrs={'required':'required','class':'form-control',}))

    def clean(self):
        all_clean_data = super( AddBetForm,self).clean()
        gameCode    = all_clean_data['gameCode']

betcroquet_app/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect
from django.utils.translation import gettext as _
#
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from user_mgmt_app.models import  UserProfileInfo,FriendRelationship
from betcroquet_app.models import BetCollection,Bet,BetTemplate
from user_mgmt_app.forms import  FriendForm
from betcroquet_app import forms as betForms
from betcroquet_app.forms import AddBetForm
# Create your views here.
def index(request):
    if  request.user.is_authenticated:
        #FIRST CHECK ALL BETS FROM USER
        #SECOND ADD FORM TO ADD Bet
        #THIRD ADD FORM TO CREATE BET
        user_bets           = Bet.objects.filter(user=request.user).values()
        bet_cards           = []
        bet_cards_completed = []
        addBetForm  = betForms.AddBetForm()
        data = {}
        data['addBetForm'] = addBetForm
        for bet in user_bets:

            bet_collection = BetCollection.objects.get(pk= bet['betCollection_id'])
            bet_template    = BetTemplate.objects.get(  pk = bet_collection.template.id)
            card ={'template':bet_template.name,
                   'templateDes':bet_template.description,
                   'name':bet_collection.name,
                   'gameCode':bet_collection.gameCode,
                   'collectionDes':bet_collection.description,
                   'closeDate':bet_collection.closeDate,
                   'state':bet_template.state,
                   'image':('/media/{}').format(bet_template.image),}
            if card['state']:
                bet_cards_completed.append(card)
            else:
                bet_cards.append(card)



        data['bet_cards'] = bet_cards
        data['bet_cards_completed'] = bet_cards_completed
        if request.method == 'POST':
            addBet = betForms.AddBetForm(data=request.POST)

            if addBet.is_valid():
                post_gameCode = request.POST.get('gameCode')
                print('==================================================',post_gameCode)
                if ( BetCollection.objects.filter(gameCode=post_gameCode ).count()>0):
                    bet_collection = BetCollection.objects.get(gameCode=post_gameCode)
                    if  Bet.objects.filter(user =request.user,betCollection= bet_collection).count()>0:
                        print("YA AÑADIDA")
                    else:
                        new_bet = Bet(betCollection=bet_collection,user=request.user)
                        new_bet.save()
                        print("Bet added to user")


        return render(request,'betcroquet_app/index.html',data)
    else:
        return render(request,'betcroquet_app/index.html')

def betview(request,gameCode):
    return render(request,'betcroquet_app/betform.html')

def addBetview(request):
    return render(request,'betcroquet_app/addbet.html')

betcroquet_app/templates/betcroquet_app/addbet.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
{% block page_header %}


<div class="container">
  <div class="col-sm-12 col-md-3 col-md-offset-4">
    <h2>MAKE YOUR BET!</h2>
    <img src="/media/{{ request.session.profile_pic }}" class="perfil-img" alt="profile_pic">
  </div>
  <div class="dropdown col-sm-12 col-md-3 col-md-offset-4">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <h3>Welcome,  {{request.user.username}}<span class="caret"></span></h3>
    </a>
    <ul class="dropdown-menu avatar-drop">
      <li><a href="#">Perfil</a></li>
      <li><a href="{% url 'user_mgmt_app:user_logout' %}">Logout</a></li>
    </ul>
  </div>

</div>

{% endblock %}
{% block content %}
<div class="jumbotron orangeBg">
  <div class='container-fluid ' id='betWrapper'>
    <div class='row col-md-offset-3'>
      <span>bet name and small data</span>
    </div>
  </div>
  <div class='container-fluid wrapper yellowBg' id='betWrapper'>
    aqui formulario de apuesta
  </div>



  {% endblock %}
  {% endif %}

betcroquet_app/templates/betcroquet_app/betform.html
{% extends 'base.html' %}
{% if user.is_authenticated %}

{% block page_header %}

<div class="container">
  <div class="col-sm-12 col-md-3 col-md-offset-4">
    <h2>MAKE YOUR BET!</h2>
    <img src="/media/{{ request.session.profile_pic }}" class="perfil-img" alt="profile_pic">
  </div>
  <div class="dropdown col-sm-12 col-md-3 col-md-offset-4">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <h3> {{request.user.username}}<span class="caret"></span></h3>
    </a>
    <ul class="dropdown-menu avatar-drop">
      <li><a href="#">Perfil</a></li>
      <li><a href="{% url 'user_mgmt_app:user_logout' %}">Logout</a></li>
    </ul>
  </div>

</div>
{% endblock %}
{% block content %}
<div class="jumbotron orangeBg">
  <div class='container-fluid ' id='betWrapper'>
    <div class='row col-md-offset-3'>
      <span>bet name and small data</span>
    </div>
  </div>
  </div>
  <div class='container-fluid wrapper yellowBg' id='betWrapper'>
    aqui formulario de apuesta
  </div>



{% endblock %}
{% endif %}

betcroquet_app/templates/betcroquet_app/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block head_css_section %}
  <link href="{% static 'css/login.css' %}" rel="stylesheet" media="screen">
{% endblock head_css_section %}
{% block content %}

<div class="jumbotron text-center">
<h2>LOGIN</h2>
</div>

<div class="container-fluid ">
  <div class="container login-container col-md-6 col-md-offset-3">
    {% if login_error %}
    <h2 class= "error_warning">{{ login_error }}</h2>
    {%  endif %}

    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h2>Login:</h2>
        <form action="{% url 'user_mgmt_app:user_login' %}" method="post">
        {% csrf_token %}
          <div class="form-group">
            <label class="control-label"  for="username">Nombre de usuario:</label>
            <input class="form-control" type="text" name="username" placeholder="Nombre de Usuario">
          </div>
          <div class="form-group">
            <label class="control-label"  for="password">Contraseña:</label>
            <input class="form-control" type="password" name="password">
          </div>
          <div class="text-center" >
            <input class="btn btn-primary" type="submit" name="" value="Login">
          </div>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h2>Registrarse:</h2>
        <form action="{% url 'user_mgmt_app:register' %}">
          <div class=" text-center">
            <input class="btn btn-primary" type="submit" value="REGISTRAR" />
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

betcroquet_app/templates/betcroquet_app/index.html
{% extends 'base.html' %}
{% block head_css_page %}
{% load staticfiles %}
<link href="{% static 'css/card.css' %}" rel="stylesheet" media="screen">
{% endblock %}


{% block page_header %}


  <div class="container">
    {% if user.is_authenticated %}
    <div class="col-sm-12 col-md-3 col-md-offset-4">
      <h2>BETCROQUET! WORK IN PROGRESS!</h2>
        <a href="#"><img src="/media/{{ request.session.profile_pic }}"class="perfil-img" alt="profile_pic"></a>
    </div>
    <div class="dropdown col-sm-12 col-md-3 col-md-offset-4">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <h3>Welcome,  {{request.user.username}}<span class="caret"></span></h3>
      </a>
      <ul class="dropdown-menu avatar-drop">
        <li><a href="#">Perfil</a></li>
        <li><a href="{% url 'user_mgmt_app:user_logout' %}">Logout</a></li>
      </ul>
    </div>
    {% else %}
    <h2>
      BetCroquet is a web to make "bets" between friends about different topics like the oscars...
    </h2>
    {% endif %}
  </div>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="jumbotron orangeBg">
  <div class='container-fluid ' id='betWrapper'>
    <div class='row col-md-offset-3'>
      <form name='AddBetForm' method="post">
        {% csrf_token %}
        <div class="form-group col-md-3">
          <label for="codeInput"><h2>ADD BET</h2></label>
          {% for field in addBetForm %}
          <input type="text" name="gameCode"  class="codeInput form-control "required id={{ field.auto_id }}><button type="submit" name="button" class=' icon btn btn-primary btn-lg'> <span class='glyphicon glyphicon-search'></span></button>
          {% endfor %}
        </div>
      </form>
      <div class="form-group col-sm-12 col-md-6 ">
        <h2>CREATE A NEW BET</h2>
        <button type="button" class="btn btn-primary btn-lg disabled"  name="button">CREATE BET</button>
      </div>
    </div>
  </div>
</div>
<div class='container-fluid wrapper yellowBg' id='betWrapper'>
  {% if bet_cards %}
  <h1>Yours active bets:</h1>

    {% for card in bet_cards %}
    <div class = "col-md-4 col-sm-5">
      <div class="card hovercard ">
        <img src="{{card.image}}" alt=""/>
        <div class="info">
          <div class="title">
            {{card.template}}
          </div>
          <div class="desc">{{card.name}}</div>
          <div class="desc">{{card.closeDate}}</div>
        </div>
        <div class="bottom">
        <a class="btn btn-default"  href="{% url 'betcroquet_app:betView' card.gameCode   %}" %}>BET!</a>
        </div>
      </div>
    </div>


    {% endfor %}
    {% endif %}
    {% if bet_cards_completed %}
    <h1>Yours finished bets:</h1>

      {% for card in bet_cards_completed %}
      <div class = "col-md-4 col-sm-5">
        <div class="card hovercard">
          <img src="{{card.image}}" alt=""/>
          <div class="info">
            <div class="title">
              {{card.template}}
            </div>
            <div class="desc">{{card.name}}</div>
            <div class="desc">{{card.closeDate}}</div>
          </div>
          <div class="bottom">
            <button class="btn btn-default"  href="#" %}>BET!</button>
          </div>
        </div>
      </div>


      {% endfor %}
      {% endif %}
  </div>
  {% else %}
  <div class="jumbotron orangeBg">
    <div class='container-fluid ' id='betWrapper'>
      <div class="row">
        <h2>You must sign in or sign up before you can start enjoying betcroquet</h2>
        <div class="col-md-2 col-md-offset-5"><a type="button" class="btn btn-primary btn-lg"   href="{% url 'user_mgmt_app:user_login' %}" name="signin">SIGN IN</a></div>
        <div class="col-md-2 col-md-offset-5"><a type="button" class="btn btn-primary btn-lg"   href="{% url 'user_mgmt_app:register' %}" name="signup">SIGN UP</a></div>
      </div>
    </div>
  </div>
  {% endif %}
  {% endblock %}